version: "3.8"

services:
  seapay-processor:
    build: .
    container_name: seapay-processor
    ports:
      - "8092:8080"
    volumes:
      - /mnt/user/appdata/seapay/data:/data
      - /mnt/user/appdata/seapay/templates_pdf:/templates
      - /mnt/user/appdata/seapay/config:/config
      - /mnt/user/appdata/seapay/output:/output
